import type { SkillLevel } from "@/lib/chess/skill-level";

export type Opening = {
  slug: string;
  name: string;
  eco: string;
  /** SAN moves for a realistic full main line, from the starting position. */
  moves: string[];
  /** Explanation for each move in `moves`, same length and order. */
  moveExplanations: string[];
  /**
   * Optional "idea" arrow(s) to draw on the board after each move, same
   * length and order as `moves`. `null` for plies with no specific arrow.
   */
  moveIdeas: Array<Array<{ from: string; to: string }> | null>;
  summary: string;
  explanation: string;
  plans: { white: string; black: string };
  /** Lowest skill level this opening is surfaced to by default. */
  level: SkillLevel;
};

export const OPENINGS: Opening[] = [
  {
    slug: "italian-game",
    name: "Italian Game",
    eco: "C50",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d3", "d6", "O-O", "O-O"],
    moveExplanations: [
      "Grabs the center and opens lines for the queen and light-squared bishop.",
      "Black mirrors, claiming an equal share of the center.",
      "Develops a piece and attacks the e5 pawn.",
      "Defends e5 and develops naturally.",
      "Aims the bishop at f7, Black's weakest point.",
      "Black develops symmetrically, eyeing f2 in return.",
      "Prepares d4 to build a full center, and gives the bishop a retreat square on c2 if needed.",
      "Develops the last minor piece and attacks e4.",
      "Solidly defends e4 without yet committing to d4.",
      "Black secures e5 and opens the c8-bishop's diagonal.",
      "White tucks the king away and connects the rooks.",
      "Black does the same — both sides are fully developed and ready for the middlegame.",
    ],
    moveIdeas: [
      null,
      null,
      [{ from: "f3", to: "e5" }],
      null,
      [{ from: "c4", to: "f7" }],
      [{ from: "c5", to: "f2" }],
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "One of the oldest openings — fast, natural development aimed at f7.",
    explanation:
      "White develops the bishop straight at Black's weakest point, f7, and prepares to castle quickly. It's a great first opening because every move has an obvious purpose.",
    plans: {
      white: "Castle short, build a strong center with c3/d4, look for tactics against f7.",
      black: "Mirror development with ...Bc5 or play solidly with ...Be7/...Nf6, contest the center.",
    },
    level: "beginner",
  },
  {
    slug: "ruy-lopez",
    name: "Ruy Lopez (Spanish)",
    eco: "C60",
    moves: [
      "e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6",
      "O-O", "Be7", "Re1", "b5", "Bb3", "d6", "c3", "O-O",
    ],
    moveExplanations: [
      "Grabs the center and opens development.",
      "Black claims equal space.",
      "Develops and attacks e5.",
      "Defends e5.",
      "Pins the knight to the king, pressuring e5 indirectly since a trade would leave it undefended.",
      "Questions the bishop immediately, gaining a tempo and keeping options open.",
      "Retreats but keeps the pin along the a4-e8 diagonal.",
      "Develops and counterattacks e4.",
      "King safety, and sidesteps any tricks on the e-file.",
      "Solid development, prepares to castle.",
      "Supports e4 preemptively and prepares to meet ...b5 with Bb3.",
      "Gains space and hits the bishop, breaking the pin's connection to a4.",
      "Retreats to a safe square on the long diagonal, still eyeing f7.",
      "Solidifies e5 and frees the c8-bishop's diagonal.",
      "Prepares d4 to challenge the center — the standard Ruy Lopez plan.",
      "Black completes development and castles to safety.",
    ],
    moveIdeas: [
      null,
      null,
      [{ from: "f3", to: "e5" }],
      null,
      [{ from: "b5", to: "c6" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "b3", to: "f7" }],
      null,
      null,
      null,
    ],
    summary: "Pressures the knight defending e5, one of the most respected e4 openings.",
    explanation:
      "The bishop pins the c6-knight to indirectly attack the e5-pawn. White plays for long-term pressure rather than immediate tactics.",
    plans: {
      white: "Castle, reroute pieces (Re1, Bxc6 ideas or Ba4-b3), fight for the center with c3/d4.",
      black: "Play ...a6 to question the bishop, then develop naturally with ...Nf6, ...Be7, ...b5 lines.",
    },
    level: "intermediate",
  },
  {
    slug: "sicilian-najdorf",
    name: "Sicilian Defense — Najdorf",
    eco: "B90",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6",
      "Nc3", "a6", "Be3", "e5", "Nb3", "Be6", "f3", "Be7",
    ],
    moveExplanations: [
      "Grabs the center and invites the Sicilian.",
      "Black fights for the center asymmetrically, aiming for imbalanced, winning-try chess.",
      "Develops toward d4.",
      "Prepares ...Nf6 safely and supports a future ...e5.",
      "Strikes the center, offering a trade.",
      "Black accepts, opening the c-file for later pressure.",
      "Recaptures, centralizing the knight.",
      "Develops and attacks e4.",
      "Defends e4 and develops.",
      "The Najdorf's signature move — rules out Nb5/Bb5 ideas and keeps Black's setup flexible.",
      "Prepares the aggressive English Attack setup with Qd2/O-O-O.",
      "Grabs central space, kicking the d4-knight.",
      "Retreats to a safe, flexible square rather than trading it off.",
      "Develops and covers the a2-g8 diagonal.",
      "Shores up e4 and prepares g4 — the standard English Attack plan.",
      "Completes development, ready to castle.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "c3", to: "d5" }],
      null,
      [{ from: "e3", to: "a7" }],
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "The most respected reply to 1.e4 for players who want to play for a win as Black.",
    explanation:
      "Black delays kingside development to play ...a6 first, preventing Nb5/Bb5 ideas and preparing flexible expansion with ...e5 or ...b5.",
    plans: {
      white: "Attack quickly on the kingside (Be3/f3/Qd2/O-O-O) before Black consolidates.",
      black: "Expand with ...e5 and ...b5, aim for active piece play and counterattack.",
    },
    level: "advanced",
  },
  {
    slug: "queens-gambit-declined",
    name: "Queen's Gambit Declined",
    eco: "D30",
    moves: [
      "d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Be7",
      "e3", "O-O", "Nf3", "h6", "Bh4", "b6",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Black claims equal space.",
      "The Queen's Gambit — challenges d5 indirectly rather than defending c4.",
      "Black keeps the strong pawn on d5 rather than grabbing c4, prioritizing solidity over material.",
      "Develops and adds pressure on d5.",
      "Develops and defends d5 again.",
      "Pins the knight, increasing the pressure on d5.",
      "Breaks the pin safely and prepares to castle.",
      "Opens the dark-squared bishop's diagonal and prepares Bd3/Nf3.",
      "King safety.",
      "Completes minor piece development.",
      "Asks the bishop to clarify its intentions.",
      "Keeps the pin rather than trading, maintaining the tension.",
      "Prepares to develop the light-squared bishop via b7 — the classic plan for freeing Black's game.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      [{ from: "c3", to: "d5" }],
      null,
      [{ from: "g5", to: "d8" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "Solid, classical response to the Queen's Gambit that leads to rich strategic play.",
    explanation:
      "Black keeps the center pawn on d5 instead of grabbing the c4-pawn, prioritizing a solid structure over material.",
    plans: {
      white: "Develop naturally, consider the Exchange Variation to attack the c-file/minority attack.",
      black: "Free the light-squared bishop (...b6 or ...dxc4/...c5 breaks), aim for equality then outplay.",
    },
    level: "beginner",
  },
  {
    slug: "kings-indian-defense",
    name: "King's Indian Defense",
    eco: "E60",
    moves: [
      "d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6",
      "Nf3", "O-O", "Be2", "e5", "O-O", "Nc6",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Develops and controls e4, without committing the center pawns yet.",
      "Expands — the classic setup that invites a hypermodern reply.",
      "Prepares the King's Indian fianchetto.",
      "Develops and supports e4.",
      "Fianchettoes, eyeing the long diagonal and the center from a distance.",
      "White builds a broad classical pawn center — the point of allowing the fianchetto.",
      "Prepares ...e5, the thematic central break.",
      "Defends e4 and develops.",
      "King safety, before committing further in the center.",
      "Solid development that keeps White's plans flexible.",
      "The key King's Indian break — striking at the center from the side rather than head-on.",
      "White castles, keeping options open depending on how Black follows up.",
      "Adds pressure to d4, completing development.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      [{ from: "g7", to: "a1" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "Hypermodern setup — Black lets White build a big center, then strikes back at it.",
    explanation:
      "Black fianchettoes the bishop and castles quickly, planning a thematic ...e5 or ...c5 break to challenge White's center later with pieces fully developed.",
    plans: {
      white: "Build a broad pawn center, expand on the queenside once Black commits to ...e5.",
      black: "Play ...e5 or ...c5 at the right moment, launch a kingside pawn storm with ...f5 in many lines.",
    },
    level: "advanced",
  },
  {
    slug: "london-system",
    name: "London System",
    eco: "D02",
    moves: [
      "d4", "d5", "Nf3", "Nf6", "Bf4", "e6", "e3", "Bd6",
      "Bg3", "O-O", "Bd3", "c5", "c3", "Nc6",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Black mirrors.",
      "Develops, keeping options open.",
      "Mirrors development.",
      "The London's key idea — develop this bishop before e3 traps it behind the pawn chain.",
      "Solid, prepares ...Bd6 or ...Be7 and frees development.",
      "Supports d4 and opens the f1-bishop's diagonal.",
      "Challenges White's bishop directly, offering a trade.",
      "Avoids the trade, keeping the bishop active on the b8-h2 diagonal.",
      "King safety.",
      "Completes development, eyeing the kingside.",
      "Black strikes at the center — the typical freeing break against the London.",
      "Supports d4 solidly.",
      "Develops and adds pressure on d4.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      [{ from: "f4", to: "b8" }],
      null,
      null,
      null,
      null,
      null,
      [{ from: "d3", to: "h7" }],
      null,
      null,
      null,
    ],
    summary: "A simple, reliable setup for White that can be played almost regardless of Black's reply.",
    explanation:
      "White develops the dark-squared bishop before playing e3, avoiding the common problem of it getting stuck behind the pawn chain. Easy to learn, hard to punish.",
    plans: {
      white: "Set up Bf4, e3, Bd3/Be2, Nbd2, O-O, then expand with c3/Ne5 or a kingside plan.",
      black: "Contest the center with ...c5, or fianchetto with ...g6 to challenge the bishop's diagonal.",
    },
    level: "beginner",
  },
  {
    slug: "caro-kann",
    name: "Caro-Kann Defense",
    eco: "B10",
    moves: [
      "e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5",
      "Ng3", "Bg6", "h4", "h6", "Nf3", "Nd7",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Prepares ...d5 without blocking the light-squared bishop in.",
      "Builds a full center.",
      "Challenges it directly.",
      "Defends e4 and develops.",
      "Black resolves the tension, trading off the central pawn.",
      "Recaptures, centralizing the knight.",
      "Develops the light-squared bishop actively before playing ...e6 — the whole point of the Caro-Kann move order.",
      "Kicks the bishop while developing.",
      "Retreats but stays active, eyeing e4 and d3.",
      "Gains space and threatens h5 — a sharp try against the bishop.",
      "Stops h5 from gaining any more space.",
      "Develops toward the center.",
      "Prepares ...Ngf6 without blocking the other knight, and readies ...e6.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "f5", to: "b1" }],
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "A solid, low-risk reply to 1.e4 that avoids many sharp tactical lines.",
    explanation:
      "Black prepares ...d5 without blocking in the light-squared bishop (unlike the French Defense), aiming for a sound structure.",
    plans: {
      white: "Play for a small, lasting space advantage; the Advance Variation (e5) is popular.",
      black: "Trade central tension favorably, develop the light-squared bishop before ...e6.",
    },
    level: "intermediate",
  },
  {
    slug: "english-opening",
    name: "English Opening",
    eco: "A10",
    moves: [
      "c4", "e5", "Nc3", "Nf6", "Nf3", "Nc6", "g3", "d5",
      "cxd5", "Nxd5", "Bg2", "Nb6", "O-O", "Be7",
    ],
    moveExplanations: [
      "A flank opening — claims queenside space while staying flexible.",
      "Black grabs the center directly, effectively a reversed Sicilian.",
      "Develops and supports the center.",
      "Develops and pressures central squares.",
      "Develops and adds central control.",
      "Develops and defends e5.",
      "Prepares the standard English fianchetto.",
      "Black strikes in the center while it's available.",
      "Trades favorably into a more open position.",
      "Recaptures, centralizing the knight.",
      "Completes the fianchetto, eyeing the long diagonal and the centralized knight.",
      "Retreats the knight to a safer, still-active square.",
      "King safety.",
      "Solid development, preparing to castle.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "g2", to: "a8" }],
      null,
      null,
      null,
    ],
    summary: "A flexible flank opening that can transpose into many other structures.",
    explanation:
      "White claims space on the queenside first and keeps options open for a later d4 or a full fianchetto setup.",
    plans: {
      white: "Choose between a Reversed Sicilian setup, symmetrical structures, or transposing to d4 openings.",
      black: "Mirror with ...c5, or strike the center directly with ...e5 or ...d5.",
    },
    level: "advanced",
  },
  {
    slug: "scotch-game",
    name: "Scotch Game",
    eco: "C45",
    moves: [
      "e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nf6",
      "Nc3", "Bb4", "Nxc6", "bxc6", "Bd3", "d5", "exd5", "cxd5",
      "O-O", "O-O",
    ],
    moveExplanations: [
      "Grabs the center and opens lines for the queen and light-squared bishop.",
      "Black mirrors, claiming an equal share of the center.",
      "Develops a piece and attacks e5.",
      "Defends e5 and develops naturally.",
      "Strikes the center immediately rather than building up slowly, the Scotch's defining idea.",
      "Black takes, opening the center at once.",
      "Recaptures, centralizing the knight with tempo-gaining potential.",
      "Develops and attacks e4.",
      "Adds a second attacker to e4 and eyes c6.",
      "Pins the knight, keeping the position sharp and well-developed.",
      "Trades off the centralized knight, doubling Black's pawns.",
      "Recaptures, accepting doubled c-pawns for the bishop pair and open lines.",
      "Develops toward the kingside, eyeing h7.",
      "Strikes back in the center, freeing Black's position.",
      "Trades off the tension rather than letting Black keep a strong center.",
      "Recaptures, straightening the pawn structure.",
      "King safety, connecting the rooks.",
      "Black does the same, and both sides are ready for a balanced middlegame.",
    ],
    moveIdeas: [
      null,
      null,
      [{ from: "f3", to: "e5" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "d3", to: "h7" }],
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "An immediate central strike after 1.e4 e5 2.Nf3 Nc6 — sharper than the quiet Italian.",
    explanation:
      "Instead of building up slowly, White challenges the center right away with 3.d4, trading into an open position where the centralized knight gives quick, easy development.",
    plans: {
      white: "Use the centralized knight and bishop pair (after Nxc6) for active piece play against Black's structure.",
      black: "Accept the doubled c-pawns for the bishop pair, strike back in the center with ...d5 to free the position.",
    },
    level: "beginner",
  },
  {
    slug: "vienna-game",
    name: "Vienna Game",
    eco: "C25",
    moves: [
      "e4", "e5", "Nc3", "Nf6", "g3", "d5", "exd5", "Nxd5",
      "Bg2", "Nb6", "Nge2", "Nc6", "O-O", "Be7", "d3", "O-O",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Black claims equal space.",
      "Develops the knight before committing the f-pawn, keeping options open.",
      "Attacks e4 and develops.",
      "Prepares a kingside fianchetto instead of the sharper f4 gambit lines.",
      "Black strikes the center immediately while White's setup is still flexible.",
      "Trades, opening the position.",
      "Recaptures, centralizing the knight.",
      "Completes the fianchetto, eyeing the long diagonal.",
      "Retreats the knight to a safer, still-active square.",
      "Develops flexibly, keeping the f-pawn free to support a later f4 push.",
      "Develops and adds central control.",
      "King safety.",
      "Solid development, preparing to castle.",
      "Supports a future e4/f4 expansion without blocking the bishop.",
      "Black completes development and castles to safety.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "g2", to: "a8" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "A flexible alternative to 2.Nf3 that keeps both quiet and sharp f4 plans in reserve.",
    explanation:
      "White develops the knight to c3 before deciding how to handle the center, ready to transpose into quiet fianchetto lines or a sharp f4 gambit depending on Black's setup.",
    plans: {
      white: "Fianchetto the bishop, castle, and look for a well-timed d4 or f4 break.",
      black: "Contest the center with ...d5, develop naturally, and castle before opening the position.",
    },
    level: "beginner",
  },
  {
    slug: "french-defense-classical",
    name: "French Defense — Classical",
    eco: "C11",
    moves: [
      "e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "Be7",
      "e5", "Nfd7", "Bxe7", "Qxe7", "f4", "O-O", "Nf3", "c5",
      "Qd2", "Nc6", "O-O-O", "a6",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Prepares ...d5, striking back without blocking in the light-squared bishop.",
      "Builds a full center.",
      "Challenges it directly — the French's central tension.",
      "Defends e4 and develops.",
      "Develops and pressures e4 again.",
      "Pins the knight, adding pressure to e4 and preparing to double up on the tension.",
      "Breaks the pin safely and prepares to castle.",
      "Gains space and locks the center, the key French Advance-style structure that follows a piece trade.",
      "Retreats, since the knight is now hemmed in but can reroute or support ...c5/...f6 breaks.",
      "Trades off the pinning bishop rather than letting Black break the pin favorably.",
      "Recaptures, keeping the queen active on the kingside.",
      "Supports the e5 pawn chain and prepares a kingside pawn storm.",
      "King safety before the position gets sharp.",
      "Develops the last minor piece.",
      "Strikes at the base of White's center, the thematic French counterattack.",
      "Develops and prepares to castle long, aiming pieces at the kingside.",
      "Develops, adding pressure to d4.",
      "Castles into the attack, opposite-side castling promising a sharp race.",
      "Prepares ...b5 to gain queenside space and open lines against White's king.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "c5", to: "d4" }],
      null,
      null,
      null,
      null,
    ],
    summary: "A solid, resilient defense to 1.e4 that often leads to opposite-side castling and sharp attacking races.",
    explanation:
      "Black accepts a cramped light-squared bishop in exchange for a solid pawn chain and a clear plan: strike at White's center with ...c5 and ...f6 while both sides race to attack the opposing king.",
    plans: {
      white: "Castle long, storm the kingside with g4/h4, keep the center intact.",
      black: "Undermine the center with ...c5 and ...f6, counterattack on the queenside if White castles long.",
    },
    level: "intermediate",
  },
  {
    slug: "slav-defense",
    name: "Slav Defense",
    eco: "D10",
    moves: [
      "d4", "d5", "c4", "c6", "Nf3", "Nf6", "Nc3", "dxc4",
      "a4", "Bf5", "e3", "e6", "Bxc4", "Bb4", "O-O", "O-O",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Black mirrors, claiming equal space.",
      "The Queen's Gambit — challenges d5 indirectly.",
      "Supports d5 with the pawn instead of the knight, keeping the light-squared bishop free to develop.",
      "Develops, adding pressure on d5.",
      "Develops and defends d5 again.",
      "Develops, adding a third attacker on d5.",
      "Black takes the c4-pawn, since it can be held without shutting in the light-squared bishop.",
      "Stops ...b5 from defending the extra pawn comfortably.",
      "Develops the light-squared bishop actively before playing ...e6 — the whole point of the Slav move order.",
      "Opens the dark-squared bishop's diagonal and prepares to recapture on c4.",
      "Solidifies the center and frees the dark-squared bishop's diagonal.",
      "Recaptures the pawn, completing development.",
      "Pins the knight, adding pressure to the center.",
      "King safety.",
      "Black does the same, and both sides are fully developed.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      [{ from: "f3", to: "d5" }],
      null,
      [{ from: "c3", to: "d5" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "A solid answer to the Queen's Gambit that keeps the light-squared bishop free before locking the center.",
    explanation:
      "Unlike the Queen's Gambit Declined, Black defends d5 with the c-pawn, leaving room to develop the light-squared bishop to f5 or g4 before playing ...e6.",
    plans: {
      white: "Regain the c4-pawn, develop naturally, and look for a small central or kingside initiative.",
      black: "Develop the light-squared bishop actively first, then complete development and contest the center.",
    },
    level: "intermediate",
  },
  {
    slug: "nimzo-indian",
    name: "Nimzo-Indian Defense",
    eco: "E20",
    moves: [
      "d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "e3", "O-O",
      "Bd3", "d5", "Nf3", "c5", "O-O", "Nc6", "a3", "Bxc3",
      "bxc3", "dxc4", "Bxc4",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Develops and controls e4, keeping the center flexible.",
      "Expands.",
      "Prepares ...Bb4, the Nimzo-Indian's key idea.",
      "Pins the knight, pressuring e4 and preventing White from freely playing e4.",
      "Prepares e3 and Bd3 without allowing e4 for free.",
      "Solidifies the center, ready to meet ...Bxc3 with a recapture that keeps a strong pawn duo.",
      "King safety, before committing further.",
      "Develops naturally, keeping the bishop pair option open with Bd3.",
      "Strikes the center directly, contesting it head-on.",
      "Develops and adds support to the center.",
      "Adds pressure to d4, the standard Nimzo counter-break.",
      "King safety.",
      "Develops and adds pressure to d4.",
      "Asks the bishop to decide — trade or retreat.",
      "Black trades, doubling White's pawns in exchange for the bishop pair — the strategic heart of the opening.",
      "Recaptures, accepting doubled c-pawns for a strong pawn center and the bishop pair.",
      "Takes the c4-pawn while the center is still fluid.",
      "Recaptures, completing development with an active bishop.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      [{ from: "b4", to: "c3" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "A hypermodern classic — Black pins the c3-knight to prevent a big White center, often trading the bishop for structural damage.",
    explanation:
      "Black develops with ...Bb4 before committing the center pawns, aiming to either win the bishop pair by trading on c3 or provoke a3 and retreat with a useful tempo gained.",
    plans: {
      white: "Accept doubled c-pawns for the bishop pair and a strong center, or avoid the trade with an early Nge2.",
      black: "Pressure the doubled c-pawns and the center with ...c5 and ...d5, trade into a favorable structure.",
    },
    level: "advanced",
  },
  {
    slug: "sicilian-dragon",
    name: "Sicilian Defense — Dragon (Yugoslav Attack)",
    eco: "B76",
    moves: [
      "e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6",
      "Nc3", "g6", "Be3", "Bg7", "f3", "O-O", "Qd2", "Nc6",
      "Bc4", "Bd7", "O-O-O", "Rc8", "Bb3", "Ne5",
    ],
    moveExplanations: [
      "Grabs the center and invites the Sicilian.",
      "Black fights for the center asymmetrically.",
      "Develops toward d4.",
      "Prepares ...Nf6 and a future ...g6.",
      "Strikes the center, offering a trade.",
      "Black accepts, opening the c-file.",
      "Recaptures, centralizing the knight.",
      "Develops and attacks e4.",
      "Defends e4 and develops.",
      "The Dragon's signature move — fianchettoes the bishop onto the long diagonal aimed at White's queenside.",
      "Prepares the Yugoslav Attack setup with f3/Qd2/O-O-O.",
      "Completes the fianchetto, the bishop now eyeing c3 and the a1-h8 diagonal.",
      "Shores up e4 and prepares g4 — a direct kingside pawn storm since both sides will castle opposite.",
      "King safety, before the position turns into an attacking race.",
      "Prepares to castle long and connect the attack with Bh6 or h4-h5 ideas.",
      "Develops and adds pressure to d4.",
      "Aims the bishop at f7, tucking it away from a future ...Nxd4/...Bxd4 exchange.",
      "Develops, preparing ...Rc8 and connecting the rooks.",
      "Castles into the coming race — both kings will now be attacked with pawn storms.",
      "Prepares ...Nxd4 and ...b5, opening the c-file toward White's king.",
      "Retreats out of any future ...Nxd4 tactics while keeping the bishop's diagonal.",
      "Repositions toward c4 or d3, adding pressure and preparing ...Nc4 or ...Nc6-e5-c4 maneuvers.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "g7", to: "a1" }],
      null,
      null,
      null,
      null,
      [{ from: "c4", to: "f7" }],
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "The sharpest Sicilian of all — both sides castle to opposite wings and race pawn storms at each other's king.",
    explanation:
      "Black's fianchettoed bishop is a long-term asset on the long diagonal, but White's Yugoslav Attack (Be3/f3/Qd2/O-O-O) launches a direct kingside pawn storm — precise, memorized play matters more here than almost anywhere else in chess.",
    plans: {
      white: "Storm the kingside with h4-h5, trade off the Dragon bishop, and mate before Black's counterplay arrives.",
      black: "Race on the queenside with ...Nxd4, ...b5-b4, and open the c-file against White's king.",
    },
    level: "advanced",
  },
  {
    slug: "grunfeld-defense",
    name: "Grünfeld Defense",
    eco: "D80",
    moves: [
      "d4", "Nf6", "c4", "g6", "Nc3", "d5", "cxd5", "Nxd5",
      "e4", "Nxc3", "bxc3", "Bg7", "Nf3", "c5", "Rb1", "O-O",
      "Be2", "Nc6", "O-O", "Qc7",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Develops and controls e4.",
      "Expands.",
      "Prepares a fianchetto rather than the King's Indian's ...d6.",
      "Develops and supports the center.",
      "The Grünfeld's central strike — Black offers to trade in the center at once rather than let White simply expand.",
      "Trades, opening the position.",
      "Recaptures with the knight, keeping the position dynamic.",
      "Builds a broad pawn center — the point of allowing the trade on d5.",
      "Trades again, aiming to undermine the big center with piece pressure rather than pawns.",
      "Recaptures, keeping a strong but slightly overextended pawn duo.",
      "Fianchettoes, putting maximum pressure on d4 from a distance — the whole strategic point of the opening.",
      "Develops and defends d4.",
      "Strikes at the base of White's center immediately.",
      "Prepares to meet ...cxd4 with cxd4 without losing the b-file, and pre-empts ...Qa5 ideas.",
      "King safety.",
      "Solid development.",
      "Develops and adds pressure to d4.",
      "King safety.",
      "Adds another attacker on the c-file and prepares ...Rd8 or ...Bg4 against the center.",
    ],
    moveIdeas: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "g7", to: "a1" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    summary: "A hypermodern counterpunch — Black hands White a big center on purpose, then bombards it with pieces.",
    explanation:
      "Black trades in the center early and fianchettoes the bishop, betting that White's imposing pawn duo on c3/d4/e4 will become a target for piece pressure rather than a lasting advantage.",
    plans: {
      white: "Maintain and advance the center pawns, use the extra space for a kingside or central attack.",
      black: "Pressure d4 with ...c5, ...Bg4, and ...Nc6, aim to win the center pawns or force favorable exchanges.",
    },
    level: "expert",
  },
  {
    slug: "marshall-attack",
    name: "Ruy Lopez — Marshall Attack",
    eco: "C89",
    moves: [
      "e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6",
      "O-O", "Be7", "Re1", "b5", "Bb3", "O-O", "c3", "d5",
      "exd5", "Nxd5", "Nxe5", "Nxe5", "Rxe5", "c6", "d4", "Bd6",
      "Re1", "Qh4", "g3", "Qh3",
    ],
    moveExplanations: [
      "Grabs the center.",
      "Black claims equal space.",
      "Develops and pins the knight to pressure e5.",
      "Questions the bishop, gaining a tempo.",
      "Retreats, keeping the pin.",
      "Develops and counterattacks e4.",
      "King safety.",
      "Solid development.",
      "Supports e4 and prepares to meet ...b5 with Bb3.",
      "Gains space and hits the bishop.",
      "Retreats, still eyeing f7.",
      "Prepares d4 as usual, seemingly routine.",
      "Instead of the normal ...d6, Black launches the Marshall Gambit — sacrificing a pawn for a lasting, dangerous initiative.",
      "Opens the center immediately to try to justify the sacrifice.",
      "Recaptures with the pawn.",
      "Recaptures with the knight, centralizing it.",
      "Takes the offered pawn, accepting the gambit.",
      "Black trades, opening the e-file toward White's king.",
      "Recaptures, but the rook is now exposed on an open file facing Black's coming pieces.",
      "Gains a tempo on the rook while opening lines for the light-squared bishop.",
      "Retreats to a safe central square, defending the extra pawn.",
      "Develops with tempo, aiming the bishop at h2 and preparing ...Qh4.",
      "Retreats to a safe square, still defending the extra material.",
      "Brings the queen into the attack, threatening mate ideas on h2.",
      "The only way to defend h2 without losing more material.",
      "Pushes the queen back while further weakening the dark squares around White's king — this is the point of Black's whole sacrifice.",
    ],
    moveIdeas: [
      null,
      null,
      [{ from: "f3", to: "e5" }],
      null,
      [{ from: "b5", to: "c6" }],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [{ from: "d6", to: "h2" }],
      null,
      [{ from: "h4", to: "h2" }],
      null,
      null,
    ],
    summary: "Black gives up a pawn for permanent, world-class attacking chances against White's king — a favorite of aggressive players.",
    explanation:
      "Instead of playing the solid ...d6, Black sacrifices a pawn with 8...d5 to rip open the center and the e-file, trading material for a long-lasting initiative that has scored well even against top-level preparation.",
    plans: {
      white: "Consolidate the extra pawn, trade pieces to blunt the attack, and try to reach a favorable endgame.",
      black: "Keep pieces on, target the kingside dark squares and the king, and use the initiative before it fades.",
    },
    level: "expert",
  },
];

export function getOpening(slug: string): Opening | undefined {
  return OPENINGS.find((opening) => opening.slug === slug);
}
