import type { SequenceMotif } from "@/lib/chess/lichess-exercise";
import type { SkillLevel } from "@/lib/chess/skill-level";

export type SequenceTheme = "tactics" | "checkmate-patterns" | "endgame" | "positional";

export type Sequence = {
  slug: string;
  title: string;
  theme: SequenceTheme;
  level: SkillLevel;
  summary: string;
  /** FEN of the position the sequence starts from. */
  startFen: string;
  /** SAN moves to step through, one at a time. */
  moves: string[];
  /** Explanation shown after each move in `moves`, same length as `moves`. */
  explanations: string[];
  /** Two escalating verbal hints for puzzle (solve) mode. A 3rd, automatic hint shows the move as an arrow. */
  hints: [string, string];
  /** Lichess puzzle theme ("angle") to pull live "Exercise" puzzles from. Absent = no Exercise button. */
  motif?: SequenceMotif;
};

export const SEQUENCES: Sequence[] = [
  {
    slug: "knight-fork",
    motif: "fork",
    title: "Knight Fork",
    theme: "tactics",
    level: "beginner",
    summary: "A knight jumps to a square where it attacks the king and a rook at the same time.",
    startFen: "r3k3/8/8/1N6/8/8/8/6K1 w - - 0 1",
    moves: ["Nc7+", "Kd8", "Nxa8"],
    explanations: [
      "The knight jumps to c7, forking the king and the rook. A fork is when one piece attacks two valuable targets at once — the opponent can only save one.",
      "Black has no way to save both pieces and must move the king out of check.",
      "White simply captures the rook, coming out a full rook ahead.",
    ],
    hints: ["Look for a knight move that gives check.", "The knight can jump to c7 — what does that attack?"],
  },
  {
    slug: "absolute-pin",
    motif: "pin",
    title: "Absolute Pin",
    theme: "tactics",
    level: "beginner",
    summary: "A pinned piece can't move without exposing its own king to check — so it can be won for free.",
    startFen: "4k3/8/2n5/1B6/8/8/8/4K3 w - - 0 1",
    moves: ["Bxc6+", "Kd8"],
    explanations: [
      "The knight on c6 was pinned to the king along the b5–e8 diagonal, so it could never move to block or capture the bishop. White simply takes it, with check.",
      "Black has to step the king out of check. White is now a full piece ahead — this is why pinned pieces are often not really 'defending' anything.",
    ],
    hints: [
      "The black knight is pinned and can't move — is it defended by anything else?",
      "Capture on c6 with check.",
    ],
  },
  {
    slug: "back-rank-mate",
    motif: "backRankMate",
    title: "Back-Rank Mate",
    theme: "checkmate-patterns",
    level: "beginner",
    summary: "A king trapped behind its own pawns can be mated by a rook or queen along the back rank.",
    startFen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
    moves: ["Ra8#"],
    explanations: [
      "Black's own pawns on f7, g7 and h7 block every escape square. With the a-file completely open and nothing able to block or capture on a8, the rook delivers checkmate along the back rank — watch out for this pattern in almost every endgame.",
    ],
    hints: ["Black's king has no escape squares — look at the back rank.", "Move your rook all the way to a8."],
  },
  {
    slug: "smothered-mate",
    motif: "smotheredMate",
    title: "Smothered Mate",
    theme: "checkmate-patterns",
    level: "advanced",
    summary: "A knight delivers mate to a king that is completely boxed in by its own pieces.",
    startFen: "6rk/6pp/3N4/8/8/8/8/6K1 w - - 0 1",
    moves: ["Nf7#"],
    explanations: [
      "Black's own rook and pawns occupy every square around the king, so it has no flight squares — and nothing on the board can capture a knight on f7. This 'smothered mate' pattern, often set up with a queen sacrifice, is one of the most famous in chess.",
    ],
    hints: ["The black king is completely boxed in by its own pieces.", "Jump the knight to f7."],
  },
  {
    slug: "kings-in-opposition",
    title: "The Opposition",
    theme: "endgame",
    level: "intermediate",
    summary: "Kings can never stand next to each other — learning to use that rule is the foundation of king-and-pawn endgames.",
    startFen: "8/4k3/8/4K3/8/8/8/8 w - - 0 1",
    moves: ["Kd5"],
    explanations: [
      "White can't play Ke6 — kings are never allowed to stand adjacent to each other. Instead White sidesteps to d5, waiting for a moment to advance. Whoever is forced to give way first when the kings face off is said to have 'lost the opposition' — a key idea in almost every king-and-pawn endgame.",
    ],
    hints: [
      "You can't move directly toward the enemy king — think about keeping a safe distance while gaining ground.",
      "Step the king sideways to d5.",
    ],
  },
  {
    slug: "discovered-check",
    motif: "discoveredCheck",
    title: "Discovered Check",
    theme: "tactics",
    level: "intermediate",
    summary: "Moving one piece out of the way can reveal a check from a piece behind it.",
    startFen: "8/8/7k/8/8/8/3N4/2B3K1 w - - 0 1",
    moves: ["Nb3+", "Kg6"],
    explanations: [
      "The knight was blocking the bishop's own diagonal toward h6. Moving it away uncovers a check from the bishop — a discovered check, where the piece that moves isn't the one giving check, so it's often free to do something else useful (here, attacking) at the same time.",
      "Black must move the king out of the bishop's line of attack.",
    ],
    hints: ["Something is blocking your own bishop's diagonal.", "Move the knight away from d2 — try b3."],
  },
  {
    slug: "skewer",
    motif: "skewer",
    title: "Skewer",
    theme: "tactics",
    level: "intermediate",
    summary: "Like a pin in reverse: attack a valuable piece that must move, exposing a weaker piece behind it.",
    startFen: "6r1/5k2/8/8/8/8/8/5B1K w - - 0 1",
    moves: ["Bc4+", "Ke7", "Bxg8"],
    explanations: [
      "The bishop checks the king along the same diagonal that the rook on g8 sits on. The king — the more valuable target — has to move first.",
      "Black steps out of check, but the rook behind was left completely undefended.",
      "With the king out of the way, the bishop simply captures the rook it was 'seeing through' all along.",
    ],
    hints: ["The enemy king and rook are lined up on the same diagonal.", "Give check with the bishop from c4."],
  },
  {
    slug: "deflection",
    motif: "deflection",
    title: "Deflection",
    theme: "tactics",
    level: "advanced",
    summary: "Force a defending piece away from the square or piece it's protecting, then exploit the gap.",
    startFen: "6k1/8/r2q4/1B6/8/8/8/4R1K1 w - - 0 1",
    moves: ["Re8+", "Qf8", "Bxa6"],
    explanations: [
      "The rook check forces Black to respond immediately — and the queen is the only piece that can block on f8.",
      "Blocking the check is natural, but it deflects the queen away from the 6th rank, where it was the only thing defending the rook on a6.",
      "With the defender deflected, White simply picks up the now-undefended rook.",
    ],
    hints: [
      "The black queen is the only defender of the rook on a6 — how can you force it away?",
      "Check the king with your rook on e8.",
    ],
  },
  {
    slug: "zwischenzug",
    motif: "intermezzo",
    title: "Zwischenzug (In-Between Move)",
    theme: "tactics",
    level: "advanced",
    summary: "Before making the 'obvious' recapture, insert a forcing move first.",
    startFen: "4k3/8/8/4b3/8/5N2/4B3/6K1 w - - 0 1",
    moves: ["Bb5+", "Kd8", "Nxe5"],
    explanations: [
      "Instead of immediately recapturing on e5, White throws in a check first — the 'in-between move' (zwischenzug). It costs Black a tempo before anything else can happen.",
      "Black has to deal with the check right away, unable to contest e5.",
      "Only now does White recapture the bishop, having gained a free check along the way that a direct recapture wouldn't have earned.",
    ],
    hints: ["Don't recapture right away — is there a stronger move first?", "Give check with the bishop on b5."],
  },
  {
    slug: "removing-the-defender",
    motif: "capturingDefender",
    title: "Removing the Defender",
    theme: "tactics",
    level: "advanced",
    summary: "Trade off the piece that's guarding something, then take what it was guarding.",
    startFen: "6k1/6p1/5n2/6B1/4n3/2N5/8/6K1 w - - 0 1",
    moves: ["Bxf6", "gxf6", "Nxe4"],
    explanations: [
      "The knight on f6 was the only piece defending the knight on e4. White trades it off first.",
      "Black recaptures with the pawn — a reasonable choice, but it doesn't restore the defense of e4.",
      "With the defender gone, White wins the second knight for free.",
    ],
    hints: [
      "One black knight is defending the other — deal with the defender first.",
      "Capture the knight on f6.",
    ],
  },
  {
    slug: "greek-gift",
    title: "Greek Gift Sacrifice (Bxh7+)",
    theme: "tactics",
    level: "advanced",
    summary: "A classic bishop sacrifice on h7 (or h2) that rips open the enemy king's shelter.",
    startFen: "6k1/5ppp/8/8/8/3B1N2/8/3Q2K1 w - - 0 1",
    moves: ["Bxh7+", "Kxh7", "Ng5+", "Kg8", "Qh5"],
    explanations: [
      "White sacrifices the bishop for a pawn, dragging the king out of its shelter — the classic 'Greek gift'.",
      "Taking is close to forced; declining leaves White simply up a pawn with the attack still coming.",
      "The knight joins with check, gaining another tempo and eyeing further inroads near the king.",
      "The king has to retreat, further boxed in by its own pawns.",
      "The queen swings over to h5, aiming straight at h7 and g6 — Black's position is falling apart with no good defense left.",
    ],
    hints: [
      "A well-known sacrifice on h7 rips open the king's cover.",
      "Capture the pawn on h7 with your bishop, giving check.",
    ],
  },
  {
    slug: "decoy",
    motif: "attraction",
    title: "Decoy",
    theme: "tactics",
    level: "advanced",
    summary: "A sacrifice lures a piece onto a square where a second tactic — here, a fork — can hit it.",
    startFen: "1r2k3/8/8/3QN3/8/8/8/6K1 w - - 0 1",
    moves: ["Qd8+", "Kxd8", "Nc6+"],
    explanations: [
      "The queen sacrifices itself with check, decoying the king onto d8 — a square a knight can fork next.",
      "Capturing looks natural, since nothing else can deal with the check and the queen isn't defended.",
      "The knight jumps in with check, forking the king and the rook on b8 at once. The sacrifice pays for itself and then some.",
    ],
    hints: [
      "A sacrifice can force the king onto a square where a knight fork is waiting.",
      "Give check with the queen on d8.",
    ],
  },
  {
    slug: "overload",
    motif: "deflection",
    title: "Overload",
    theme: "tactics",
    level: "advanced",
    summary: "One defender can't cover two jobs at once — attack the piece it's least willing to give up.",
    startFen: "3n3k/8/8/1r1q2B1/3N4/8/8/6K1 w - - 0 1",
    moves: ["Nxb5", "Qxb5", "Bxd8"],
    explanations: [
      "The black queen was defending both the rook on b5 and the knight on d8 at the same time — it can't do both once one of them is attacked.",
      "Recapturing saves the rook, but the queen is no longer defending the knight on d8.",
      "With the queen pulled away, White simply picks up the knight too. The overloaded defender couldn't hold both.",
    ],
    hints: [
      "The black queen is doing two jobs — find the piece it's defending that's least protected.",
      "Capture the rook on b5 first.",
    ],
  },
  {
    slug: "anastasias-mate",
    motif: "anastasiaMate",
    title: "Anastasia's Mate",
    theme: "checkmate-patterns",
    level: "advanced",
    summary: "A knight seals off the king's escape squares while a rook delivers mate along the edge of the board.",
    startFen: "7k/4N1p1/8/8/8/8/K7/R7 w - - 0 1",
    moves: ["Rh1#"],
    explanations: [
      "The knight on e7 covers g8, the pawn on g7 blocks the only other nearby square, and the rook comes all the way down the open h-file. The king can't step off the file — it's still in check everywhere along it — and has nowhere else to go. Checkmate.",
    ],
    hints: [
      "The king is stuck on the edge of the board, and the knight already covers its one escape square.",
      "Bring the rook all the way down to the h-file.",
    ],
  },
  {
    slug: "bodens-mate",
    motif: "bodenMate",
    title: "Boden's Mate",
    theme: "checkmate-patterns",
    level: "advanced",
    summary: "Two bishops on crossing diagonals trap a king that's boxed in by its own pieces.",
    startFen: "1bkr4/2p5/8/8/B7/8/8/4KB2 w - - 0 1",
    moves: ["Ba6#"],
    explanations: [
      "One bishop already covers d7 from a4. The other swings all the way to a6, delivering check along the a6–c8 diagonal. The king's own bishop, pawn and rook block every other square, and nothing can capture the checking bishop or block the single gap on b7. Checkmate — a classic pattern that often follows a queen sacrifice to clear the diagonal.",
    ],
    hints: [
      "Two bishops on crossing diagonals, with the king's own pieces blocking its escape.",
      "Move the second bishop all the way to a6.",
    ],
  },
  {
    slug: "hanging-piece",
    motif: "hangingPiece",
    title: "Hanging Piece",
    theme: "tactics",
    level: "beginner",
    summary: "The simplest tactic of all: a piece nobody is protecting is free to take.",
    startFen: "4k3/8/8/3r4/8/8/8/3QK3 w - - 0 1",
    moves: ["Qxd5"],
    explanations: [
      "The rook on d5 has no defender at all — free material. Always scan for pieces nobody is protecting before looking for anything fancier.",
    ],
    hints: ["Look at the black rook — is anything protecting it?", "Just capture it: Qxd5."],
  },
  {
    slug: "en-passant",
    motif: "enPassant",
    title: "En Passant",
    theme: "tactics",
    level: "beginner",
    summary: "A pawn that jumps two squares past yours can still be captured, just this once.",
    startFen: "rnbqkbnr/ppp2ppp/4p3/3pP3/8/8/PPPP1PPP/RNBQKBNR w KQkq d6 0 3",
    moves: ["exd6"],
    explanations: [
      "Black's pawn just advanced two squares from d7 to d5, landing right beside White's e5 pawn. The special en passant rule lets White capture it as if it had only moved one square, playing exd6 — but only on this very next move, or the right disappears for good.",
    ],
    hints: [
      "A black pawn just jumped two squares past yours — there's a special rule for that.",
      "Capture on d6, as if the pawn had only moved one square.",
    ],
  },
  {
    slug: "attacking-f7",
    motif: "attackingF2F7",
    title: "Attacking f7",
    theme: "tactics",
    level: "beginner",
    summary: "f7 (or f2 for Black) is defended only by the king in the opening — a favorite early target.",
    startFen: "r1bqkb1r/ppp2ppp/2n5/3np1N1/2B5/8/PPPP1PPP/RNBQK2R w KQkq - 0 6",
    moves: ["Nxf7", "Kxf7", "Qf3+"],
    explanations: [
      "f7 is defended only by the king in the opening, making it a classic target. The knight jumps in, forking the queen on d8 and the rook on h8, and can't safely be ignored.",
      "Declining the knight leaves White simply a piece up with the attack still raging, so Black is more or less forced to recapture.",
      "With the king dragged to f7, the queen swings over with check, adding the bishop's diagonal to the attack — Black's position is already in serious trouble.",
    ],
    hints: ["f7 is defended only by the king this early — is anything attacking it twice?", "Jump the knight into f7."],
  },
  {
    slug: "discovered-attack",
    motif: "discoveredAttack",
    title: "Discovered Attack",
    theme: "tactics",
    level: "intermediate",
    summary: "Moving a piece out of its own line of fire can unveil an attack from the piece behind it.",
    startFen: "3qk3/8/2n5/8/3N4/8/8/3RK3 w - - 0 1",
    moves: ["Nxc6", "Qd6"],
    explanations: [
      "The knight was sitting on the d-file, blocking its own rook's view of the queen on d8. Capturing the undefended knight on c6 also unveils the rook's attack on the queen — two birds, one move.",
      "The queen has to move off the d-file at once, since the rook was about to win it for nothing.",
    ],
    hints: ["A piece of yours is blocking your own rook's attack on the queen.", "Capture the knight on c6 — see what it reveals."],
  },
  {
    slug: "trapped-piece",
    motif: "trappedPiece",
    title: "Trapped Piece",
    theme: "tactics",
    level: "intermediate",
    summary: "A piece with nowhere safe to run can be hunted down for free, one escape square at a time.",
    startFen: "N2qk3/1p6/8/8/8/8/8/4K3 b - - 0 1",
    moves: ["b6"],
    explanations: [
      "White's knight ventured to a8 and has only two ways home: b6 and c7. The queen on d8 already covers c7, and now the pawn advance to b6 shuts the door on the other one — the knight has no legal way out and will be lost.",
    ],
    hints: [
      "The knight in the corner only has two squares to escape to — can you cover them both?",
      "Push the pawn to b6, closing off one of the two squares.",
    ],
  },
  {
    slug: "defensive-move",
    motif: "defensiveMove",
    title: "Defensive Move",
    theme: "tactics",
    level: "intermediate",
    summary: "Sometimes only one exact move holds a position together — everything else loses.",
    startFen: "r6k/8/8/8/4Q3/8/5PPP/6K1 b - - 0 1",
    moves: ["Ra1+", "Qe1"],
    explanations: [
      "Black checks along the completely open back rank — with the king boxed in by its own pawns, White has no flight square.",
      "The only way to survive is to block the check exactly on e1. Any other response allows mate next move — this is the single move that holds the position together.",
    ],
    hints: ["White's king has no escape squares — this check must be blocked, not run from.", "Interpose the queen on e1."],
  },
  {
    slug: "advanced-pawn",
    motif: "advancedPawn",
    title: "Advanced Pawn",
    theme: "tactics",
    level: "intermediate",
    summary: "A pawn deep in enemy territory, close to promoting, can be worth more than it looks.",
    startFen: "4k3/P7/8/8/8/8/8/R3K3 w - - 0 1",
    moves: ["a8=Q+"],
    explanations: [
      "The pawn is one step from the back rank with nothing in its way and nothing able to stop it — 'advanced' pawns like this are often worth more than they look, since the threat to promote can decide a game all on its own. Here it simply queens, with check.",
    ],
    hints: ["Nothing stands between your pawn and the last rank.", "Push it all the way to a queen."],
  },
  {
    slug: "double-check",
    motif: "doubleCheck",
    title: "Double Check",
    theme: "tactics",
    level: "advanced",
    summary: "When a move checks with two pieces at once, the king can't block or capture its way out.",
    startFen: "7k/8/8/4N3/8/8/1B6/6K1 w - - 0 1",
    moves: ["Nf7+", "Kg8"],
    explanations: [
      "The knight was blocking its own bishop's long diagonal. Jumping to f7 both attacks the king itself and unveils the bishop's check along b2-h8 — two checks from two pieces at once, a double check.",
      "In a double check, capturing or blocking can only ever deal with one of the two checking pieces — the king must move. Here it has just one legal square.",
    ],
    hints: ["Moving the knight both attacks the king directly and reveals another check behind it.", "Jump the knight to f7."],
  },
  {
    slug: "x-ray-attack",
    motif: "xRayAttack",
    title: "X-Ray Attack",
    theme: "tactics",
    level: "advanced",
    summary: "A piece can defend a square right through an enemy piece standing in front of it.",
    startFen: "4k3/P7/8/8/r7/8/8/R3K3 w - - 0 1",
    moves: ["a8=Q+", "Rxa8", "Rxa8"],
    explanations: [
      "The pawn promotes to a queen with check. It looks like it's simply handing the queen to the black rook next move, but the White rook on a1 is watching the whole a-file behind it.",
      "Black captures the new queen — the only way to deal with the check.",
      "Because the White rook was defending a8 the entire time, right through the black rook that just moved there, White simply recaptures. The pawn's promotion cost nothing in the end.",
    ],
    hints: ["Your rook on a1 is watching the a-file all the way to a8 — even through Black's rook.", "Push the pawn to the queening square."],
  },
  {
    slug: "interference",
    motif: "interference",
    title: "Interference",
    theme: "tactics",
    level: "advanced",
    summary: "Landing a piece between two enemy pieces can cut a defense clean in half.",
    startFen: "7k/3q2b1/3N4/8/2B5/8/8/4K1R1 w - - 0 1",
    moves: ["Nf7+", "Kg8", "Rxg7+"],
    explanations: [
      "The knight jumps to f7 with check — and in doing so, plants itself right on the 7th rank between the black queen on d7 and the bishop on g7, cutting the queen's defense of it.",
      "The king has to move out of check, unable to address what's happening on g7.",
      "With the queen's defense of g7 interrupted, the rook simply captures the bishop with check — interference paid for itself.",
    ],
    hints: ["A piece landing between the queen and the bishop would cut the defense of g7.", "Jump the knight to f7, with check."],
  },
  {
    slug: "clearance",
    motif: "clearance",
    title: "Clearance",
    theme: "tactics",
    level: "advanced",
    summary: "Sometimes your own piece is in the way — moving it off the line opens a bigger idea.",
    startFen: "7k/8/8/4P3/8/2B5/8/4K3 w - - 0 1",
    moves: ["e6+"],
    explanations: [
      "The White bishop's own pawn is sitting on e5, blocking its diagonal to h8. Advancing the pawn to e6 clears that square — and check follows immediately, since nothing stands between the bishop and the king anymore.",
    ],
    hints: ["Something is in your own bishop's way on this diagonal.", "Push the pawn forward, off the diagonal."],
  },
  {
    slug: "quiet-move",
    motif: "quietMove",
    title: "Quiet Move",
    theme: "tactics",
    level: "advanced",
    summary: "Not every winning move checks or captures — sometimes the best move does nothing at all, on purpose.",
    startFen: "4k1r1/7p/8/3R4/8/8/8/7K w - - 0 1",
    moves: ["Kh2"],
    explanations: [
      "There's no check or capture here, and nothing is immediately threatened — but stepping the king off the back rank rules out any future back-rank tricks, so the rook's advance next move will simply win material with nothing to worry about. Quiet moves like this are often harder to find than a flashy tactic, precisely because they don't shout for attention.",
    ],
    hints: ["Nothing needs to happen on this move — think about what could go wrong later instead.", "Tuck the king away to h2."],
  },
  {
    slug: "exchange-sacrifice",
    motif: "sacrifice",
    title: "Exchange Sacrifice",
    theme: "tactics",
    level: "advanced",
    summary: "Giving up material now can buy an attack, or a position, worth far more than it cost.",
    startFen: "6k1/5npp/8/8/8/8/8/3Q1RK1 w - - 0 1",
    moves: ["Rxf7", "Kxf7", "Qh5+"],
    explanations: [
      "The knight on f7 is only defended by the king — White gives up the exchange (a rook for a knight) to drag that king out into the open.",
      "Recapturing is practically forced, since ignoring the threat leaves White simply up a piece.",
      "With the king now exposed on f7, the queen swings over with check — the material given up buys a dangerous, lasting attack that's worth much more than a rook.",
    ],
    hints: ["Material doesn't matter if you can rip the enemy king into the open.", "Give up the exchange on f7."],
  },
  {
    slug: "zugzwang",
    motif: "zugzwang",
    title: "Zugzwang",
    theme: "endgame",
    level: "expert",
    summary: "Being forced to move can itself be the disadvantage — every option here only makes things worse.",
    startFen: "4k3/8/4K3/8/8/8/8/4R3 b - - 0 1",
    moves: ["Kd8"],
    explanations: [
      "Black has no good moves at all — the king can't approach White's king (kings can never stand adjacent) and any step sideways only gives up more ground. This is zugzwang: being forced to move is itself the disadvantage, since literally anything Black plays here makes the position worse.",
    ],
    hints: [
      "Every move available here makes Black's position worse — that's the whole idea.",
      "Step the king to d8, the only legal option that doesn't lose immediately.",
    ],
  },
  {
    slug: "collinear-move",
    motif: "collinearMove",
    title: "Collinear Move",
    theme: "tactics",
    level: "expert",
    summary: "Two pieces already facing off on the same line don't always need to trade right away.",
    startFen: "r3k3/8/8/8/8/8/8/R3K3 w - - 0 1",
    moves: ["Ra5"],
    explanations: [
      "White's rook and Black's rook are already facing off on the open a-file. Instead of trading immediately, White slides along that very same line — repositioning the rook to a more active square while keeping the standoff exactly as it was, ready to double up or switch files later.",
    ],
    hints: ["Your rook and the enemy rook are already staring at each other on the same file.", "Slide your rook further up that same file, without trading."],
  },
  {
    slug: "arabian-mate",
    motif: "arabianMate",
    title: "Arabian Mate",
    theme: "checkmate-patterns",
    level: "intermediate",
    summary: "A knight seals off both of the king's escape squares while the rook mates from a distance.",
    startFen: "7k/6p1/5N2/8/8/8/8/R3K3 w - - 0 1",
    moves: ["Ra8#"],
    explanations: [
      "The knight on f6 already covers both g8 and h7 — the only two squares the king could otherwise run to. Black's own pawn seals off g7. With every flight square accounted for, the rook simply marches down the open a-file to deliver mate — the classic knight-and-rook 'Arabian mate'.",
    ],
    hints: ["The knight already covers both of the king's escape squares.", "Bring the rook all the way to a8."],
  },
  {
    slug: "corner-mate",
    motif: "cornerMate",
    title: "Corner Mate",
    theme: "checkmate-patterns",
    level: "intermediate",
    summary: "Confine the king to the corner with a queen or rook, then let a knight deliver the final blow.",
    startFen: "k7/8/1Q2N3/8/8/8/8/4K3 w - - 0 1",
    moves: ["Nc7#"],
    explanations: [
      "The queen on b6 already controls every square the king could flee to — a7, b7 and b8 are all covered. All that's missing is the actual checking piece: the knight jumps into c7, defended by the queen, and delivers mate in the corner.",
    ],
    hints: ["The queen already covers every escape square around the corner.", "Jump the knight into c7."],
  },
  {
    slug: "epaulette-mate",
    motif: "epauletteMate",
    title: "Epaulette Mate",
    theme: "checkmate-patterns",
    level: "intermediate",
    summary: "A king's own rooks, flanking it like epaulettes on a uniform, can block its own escape.",
    startFen: "3rkr2/8/2N5/8/8/8/4Q3/4K3 w - - 0 1",
    moves: ["Qe7#"],
    explanations: [
      "Black's own rooks on d8 and f8 look like bodyguards, but they're actually blocking the king's only real escape squares — like epaulettes on its shoulders. The queen, defended by the knight on c6, delivers check right in front of the king, and with d7 and f7 also covered by the queen along the rank, there's nowhere left to go.",
    ],
    hints: ["The king's own rooks are blocking its escape, not helping it.", "Bring the queen to e7, defended by the knight."],
  },
  {
    slug: "double-bishop-mate",
    motif: "doubleBishopMate",
    title: "Double Bishop Mate",
    theme: "checkmate-patterns",
    level: "advanced",
    summary: "Two bishops on adjacent diagonals can mate a king that's boxed in by its own pieces.",
    startFen: "5bk1/7p/8/8/8/8/1B6/4KB2 w - - 0 1",
    moves: ["Bc4#"],
    explanations: [
      "One bishop is already covering the long diagonal toward the king; the other swings over to c4, adding a second beam of attack straight at g8 down the c4-g8 diagonal. Black's own bishop on f8 and pawn on h7 block the only other flight squares, so two bishops on adjacent diagonals is all it takes.",
    ],
    hints: ["One bishop already covers half the board — bring the second one into the attack.", "Move the bishop to c4."],
  },
  {
    slug: "dovetail-mate",
    motif: "dovetailMate",
    title: "Dovetail Mate",
    theme: "checkmate-patterns",
    level: "advanced",
    summary: "A queen mates right beside the king, whose own pieces block both remaining escape squares.",
    startFen: "4kr2/5p2/1N6/8/Q7/8/8/4K3 w - - 0 1",
    moves: ["Qd7#"],
    explanations: [
      "The queen checks from d7, right next to the king — defended by the knight on b6, so it can't simply be captured. Of the king's two real escape squares, f7 is blocked by Black's own pawn and f8 by Black's own rook — boxed in by its own pieces, exactly the shape that gives the 'dovetail' mate its name.",
    ],
    hints: ["The king's own pawn and rook are blocking both of its escape squares.", "Bring the queen to d7, defended by the knight."],
  },
  {
    slug: "hook-mate",
    motif: "hookMate",
    title: "Hook Mate",
    theme: "checkmate-patterns",
    level: "advanced",
    summary: "A rook, a knight, and an opposing pawn can combine to trap a king on the edge of the board.",
    startFen: "7k/4N1p1/8/8/8/R7/8/4K3 w - - 0 1",
    moves: ["Rh3#"],
    explanations: [
      "The rook swings over to the open h-file, checking the king and covering h7 along the way. The knight on e7 covers the only other flight square, g8, and Black's own pawn on g7 blocks the third — rook, knight and an opposing pawn all cooperating is the signature of a 'hook mate'.",
    ],
    hints: ["Bring your rook onto the open h-file — the knight and a black pawn cover the rest.", "Move the rook to h3."],
  },
  {
    slug: "morphys-mate",
    motif: "morphysMate",
    title: "Morphy's Mate",
    theme: "checkmate-patterns",
    level: "advanced",
    summary: "A bishop delivers the mating blow while a rook simply keeps it safe from capture.",
    startFen: "6nk/6pp/8/8/8/2B5/8/4K1R1 w - - 0 1",
    moves: ["Bxg7#"],
    explanations: [
      "The bishop captures the pawn on g7 with check, defended by the rook behind it on the g-file so the king can't simply take it back. Black's own knight on g8 and pawn on h7 block the only other squares — the bishop delivers the mate while the rook's job is purely to keep it safe.",
    ],
    hints: ["Capturing on g7 gives check — make sure that bishop is protected first.", "Capture the pawn on g7 with the bishop."],
  },
  {
    slug: "balestra-mate",
    motif: "balestraMate",
    title: "Balestra Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "A bishop delivers the checkmate while a queen stands guard and blocks the remaining escape square.",
    startFen: "6rk/6p1/7Q/8/8/2B5/8/4K3 w - - 0 1",
    moves: ["Bxg7#"],
    explanations: [
      "The bishop captures on g7 delivering check, and this time it's the queen on h6 standing guard over it, so the king can't recapture. Black's own rook on g8 blocks the other flight square, and the queen also covers h7 along the h-file — nothing left for the king.",
    ],
    hints: ["The bishop can capture on g7 with check — something needs to be defending it first.", "Capture on g7 with the bishop."],
  },
  {
    slug: "blind-swine-mate",
    motif: "blindSwineMate",
    title: "Blind Swine Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "Two rooks doubled on the 7th rank can dominate an entire 2-by-2 box around the king.",
    startFen: "7k/6R1/8/8/8/8/8/4K2R w - - 0 1",
    moves: ["Rhh7#"],
    explanations: [
      "White already has a rook doubled onto the 7th rank at g7. The second rook slides all the way up to join it on h7, delivering check — together the two rooks control every square in the 2-by-2 box around the king (g7, g8, h7, h8), the classic 'blind swine' pattern of rampaging doubled rooks.",
    ],
    hints: ["Bring your second rook onto the 7th rank to join the first.", "Slide the h-file rook up to h7."],
  },
  {
    slug: "kill-box-mate",
    motif: "killBoxMate",
    title: "Kill Box Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "A rook and queen together can dominate every square in a tight 3-by-3 box around the king.",
    startFen: "7k/8/5N2/8/8/8/8/4K1QR w - - 0 1",
    moves: ["Rh7#"],
    explanations: [
      "The rook slides in to deliver check right next to the king. The queen on g1 controls g7 and g8 all the way down the open g-file, and a knight on f6 makes sure nothing can interpose — king, rook and queen are squeezed into a tight 3-by-3 'kill box' with no way out.",
    ],
    hints: ["Your queen already covers both squares next to the king along the g-file.", "Bring the rook in to check on h7."],
  },
  {
    slug: "opera-mate",
    motif: "operaMate",
    title: "Opera Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "A rook delivers the mating check while a bishop defends it from capture — named after the famous Opera Game.",
    startFen: "6nk/6pp/6B1/8/8/8/8/4K2R w - - 0 1",
    moves: ["Rxh7#"],
    explanations: [
      "The rook captures the pawn on h7 with check — and it's defended by the bishop sitting on g6, so the king can't recapture. Black's own knight on g8 and pawn on g7 block the only other squares. This exact pattern — a rook checking with a bishop guarding it — is named after the famous 'Opera Game' mate.",
    ],
    hints: ["Capturing on h7 gives check, and the bishop is already covering that square.", "Capture the pawn on h7 with the rook."],
  },
  {
    slug: "pillsburys-mate",
    motif: "pillsburysMate",
    title: "Pillsbury's Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "A rook delivers the mate down an open file while a bishop, not a knight, helps confine the king.",
    startFen: "5Brk/8/8/8/8/R7/8/4K3 w - - 0 1",
    moves: ["Rh3#"],
    explanations: [
      "The rook slides onto the open h-file, checking the king and controlling h7 in the same move. The bishop, tucked away on f8, quietly covers g7 the whole time — Black's own rook on g8 blocks the last square. Unlike the hook mate, it's a bishop — not a knight — helping confine the king here.",
    ],
    hints: ["Slide your rook onto the open h-file — your bishop already covers the other escape square.", "Move the rook to h3."],
  },
  {
    slug: "swallowstail-mate",
    motif: "swallowstailMate",
    title: "Swallow's Tail Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "A defended queen beside a cornered king can cover both remaining squares in one V-shaped stroke.",
    startFen: "7k/8/4N3/8/8/8/1Q6/4K3 w - - 0 1",
    moves: ["Qg7#"],
    explanations: [
      "The queen delivers mate right next to the king, defended by the knight on e6. From g7 she attacks both g8 and h7 along the rank and file at once, forming the V-shaped 'swallow's tail' around the cornered king — no square left uncovered.",
    ],
    hints: ["A defended queen right next to the king in the corner covers everything around it.", "Bring the queen to g7."],
  },
  {
    slug: "triangle-mate",
    motif: "triangleMate",
    title: "Triangle Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "Queen, rook and king form a tight triangle when the rook backs up the queen's mate from one square away.",
    startFen: "7k/8/8/7R/8/8/8/1Q2K3 w - - 0 1",
    moves: ["Qh7#"],
    explanations: [
      "The queen delivers check right next to the king, and the rook — lined up behind her on the same h-file with one empty square between them — defends her against capture. Queen, rook and king form the tight three-point 'triangle' this mate is named for.",
    ],
    hints: ["Your rook is already lined up behind where the queen wants to go.", "Bring the queen all the way to h7."],
  },
  {
    slug: "vukovic-mate",
    motif: "vukovicMate",
    title: "Vuković Mate",
    theme: "checkmate-patterns",
    level: "expert",
    summary: "A rook checks beside the king while a bishop guards it and a knight seals the last escape square.",
    startFen: "7k/4N1p1/6B1/8/8/8/8/4K2R w - - 0 1",
    moves: ["Rh7#"],
    explanations: [
      "The rook checks on h7, kept safe by the bishop watching that square from g6. The knight on e7 covers the king's only other flight square, g8, while Black's own pawn on g7 blocks the third — rook, knight and a defending bishop working together give the 'Vuković mate' its name.",
    ],
    hints: ["The bishop is already guarding the square your rook wants to land on.", "Bring the rook in to check on h7."],
  },
];

export function getSequence(slug: string): Sequence | undefined {
  return SEQUENCES.find((sequence) => sequence.slug === slug);
}
